# Generated by Django 5.0.2 on 2024-03-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_companyregistration_internregistration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyregistration',
            old_name='employee_id',
            new_name='company_id',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='gender',
        ),
    ]
