# Generated by Django 5.0.2 on 2024-03-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_rename_employee_id_companyregistration_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyregistration',
            old_name='first_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='last_name',
        ),
    ]
