# Generated by Django 5.0.2 on 2024-03-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_rename_first_name_companyregistration_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internregistration',
            name='first_name',
        ),
        migrations.AddField(
            model_name='internregistration',
            name='companyid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.companyregistration'),
        ),
    ]
