# Generated by Django 5.0.2 on 2024-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_intern_companyid_alter_intern_jobid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='company_id',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
