# Generated by Django 5.0.2 on 2024-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_alter_companyregistration_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='company_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='stu_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='intern',
            name='companyid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='internregistration',
            name='intern_id',
            field=models.IntegerField(unique=True),
        ),
    ]
