# Generated by Django 5.0.2 on 2024-03-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_alter_companyregistration_company_id_alter_cv_stu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='jobid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='intern',
            name='postid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
