# Generated by Django 5.0.2 on 2024-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_alter_intern_jobid_alter_intern_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internregistration',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='internregistration',
            name='companyid',
        ),
        migrations.RemoveField(
            model_name='internregistration',
            name='id',
        ),
        migrations.RemoveField(
            model_name='internregistration',
            name='intern_id',
        ),
        migrations.AlterField(
            model_name='internregistration',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
