# Generated by Django 5.0.2 on 2024-03-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_rename_last_name_internregistration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='flyer',
            field=models.CharField(max_length=500),
        ),
    ]
