# Generated by Django 5.0.2 on 2024-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_company_interview_job_pending_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
