# Generated by Django 5.0.2 on 2024-03-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='optional_detail',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='stu_nic',
        ),
        migrations.AddField(
            model_name='cv',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(default='123@mail.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name',
            field=models.CharField(default='full name', max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='gender',
            field=models.TextField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='nic',
            field=models.TextField(default='111111111v', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='optional_details',
            field=models.TextField(default='details', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='telephone',
            field=models.IntegerField(default=94777777777),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='cv_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cv',
            name='degree',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_company',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_exp',
            field=models.TextField(),
        ),
    ]
